environment:
  P: "c:/projects/libs"

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
#init:


# clone directory
clone_folder: c:\projects\g3log

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: g3log\build\g3log.sln

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\g3log\3rdParty\gtest
  - 7z x gtest-1.7.0.zip 
  - cd c:\projects\g3log\
  - mkdir build
  - cd build 
  - cmake -G "Visual Studio 14 2015 Win64" -DADD_G3LOG_UNIT_TEST=ON ..
  - msbuild g3log.sln /p:Configuration=Release
  
# scripts to run after build
after_build:
  - msbuild RUN_TESTS.vcxproj /p:Configuration=Release
  - cd c:\projects\g3log\build\Release
  - g3log-FATAL-contract.exe

