site_name: G3log, an asynchronous "crash-safe" logger
site_author: 'Kjell Hedstrom'
site_url: https://kjellkod.github.io/g3log/
theme:
  name: material
  
docs_dir: docs/
  
nav: 
  - Introduction to G3log: index.md
  - G3log usage: g3log.md 
  - API description: API.md
  - API for custom log formatting: API_custom_formatting.md
  - Configure, Build, Package, Install and Test: building.md
  - License and contribution: contributing.md


