site_name: Test docs
site_description: 'A docs test'
site_author: 'Kjell Hedstr√∂m'
docs_dir: docs/
repo_name: 'KjellKod/g3log'
repo_url: 'https://github.com/KjellKod/g3log'
nav:
    - Home: docs/index.md
    - API Guide: docs/API.md
theme:
  name: 'material'
